// Code generated by entc, DO NOT EDIT.

package facttype

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the facttype type in the database.
	Label = "fact_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldBuiltin holds the string denoting the builtin field in the database.
	FieldBuiltin = "builtin"

	// EdgeFacts holds the string denoting the facts edge name in mutations.
	EdgeFacts = "facts"

	// Table holds the table name of the facttype in the database.
	Table = "fact_types"
	// FactsTable is the table the holds the facts relation/edge.
	FactsTable = "facts"
	// FactsInverseTable is the table name for the Fact entity.
	// It exists in this package in order to avoid circular dependency with the "fact" package.
	FactsInverseTable = "facts"
	// FactsColumn is the table column denoting the facts relation/edge.
	FactsColumn = "fact_type_facts"
)

// Columns holds all SQL columns for facttype fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldSlug,
	FieldBuiltin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
