// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/open-privacy-vault/opv/ent/runtime.go

const (
	Version = "v0.6.0"                                          // Version of ent codegen.
	Sum     = "h1:oo/a8sXPQKzHYFlVwmwOnyzBy+u8FWQsoLLqFCrOBt0=" // Sum of ent codegen.
)
