basePath: /api/v1
definitions:
  apimodel.APIAudit:
    properties:
      created_at:
        type: string
      domain:
        type: string
      http_method:
        type: string
      http_path:
        type: string
      plane:
        type: string
      sent_http_status:
        type: integer
      updated_at:
        type: string
    type: object
  apimodel.CreateGrant:
    properties:
      allowed_http_methods:
        items:
          type: string
        type: array
      domain:
        type: string
      paths:
        description: |-
          Paths represent the path the grant token can access
          We leverage KeyMatch2 to define paths https://github.com/casbin/casbin/blob/v2.25.5/util/builtin_operators_test.go#L88-L117
          For example, by default if "paths" is not set, by default it's *

              *
              /api/v1/facts
              /api/v1/facts/:id
              /api/v1/*
              /js/v1/facts
        items:
          type: string
        type: array
    type: object
  apimodel.Grant:
    properties:
      allowed_http_methods:
        items:
          type: string
        type: array
      domain:
        type: string
      paths:
        items:
          type: string
        type: array
      token:
        type: string
    type: object
  apimodel.Healthz:
    properties:
      status:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message:
        type: object
    type: object
host: localhost
info:
  contact: {}
  description: Open Privacy Vault Control Plane API.
  title: Open Privacy Vault Control Plane API
  version: "1.0"
paths:
  /api_audits:
    get:
      consumes:
      - application/json
      description: Query API Audits
      operationId: query-api-audits
      parameters:
      - description: Domain
        in: query
        name: domain
        type: string
      - description: Plane
        in: query
        name: plane
        type: string
      - description: HTTP Path
        in: query
        name: http_path
        type: string
      - description: HTTP Method
        in: query
        name: http_method
        type: string
      - description: Sent HTTP Status
        in: query
        name: sent_http_status
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Order By
        in: query
        name: order_by
        type: string
      - description: Order Desc
        in: query
        name: order_desc
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/apimodel.APIAudit'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Query API Audits
      tags:
      - Audit
  /grants:
    post:
      consumes:
      - application/json
      description: Create a grant
      operationId: create-grant
      parameters:
      - description: Create Grant parameters
        in: body
        name: createGrant
        required: true
        schema:
          $ref: '#/definitions/apimodel.CreateGrant'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.Grant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create a grant
      tags:
      - Grant
  /healthz:
    get:
      description: Show the health of the controlplane
      operationId: healthz
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.Healthz'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Show the health of the controlplane
      tags:
      - Healthz
swagger: "2.0"
tags:
- description: A grant is the unit of grant to access certain resource in OPV
  name: Grant
