basePath: /api/v1
definitions:
  apimodel.CreateGrant:
    properties:
      allowed_http_methods:
        items:
          type: string
        type: array
      domain:
        type: string
    type: object
  apimodel.Grant:
    properties:
      allowed_http_methods:
        items:
          type: string
        type: array
      domain:
        type: string
      token:
        type: string
    type: object
  apimodel.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  apimodel.Healthz:
    properties:
      status:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: Open Privacy Vault Control Plane API.
  title: Open Privacy Vault Control Plane API
  version: "1.0"
paths:
  /grants:
    post:
      consumes:
      - application/json
      description: Create a grant
      operationId: create-grant
      parameters:
      - description: Create Grant parameters
        in: body
        name: createGrant
        required: true
        schema:
          $ref: '#/definitions/apimodel.CreateGrant'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.Grant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodel.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.HTTPError'
      summary: Create a grant
      tags:
      - Grant
  /healthz:
    get:
      description: Show the health of the controlplane
      operationId: healthz
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.Healthz'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.HTTPError'
      summary: Show the health of the controlplane
      tags:
      - Healthz
swagger: "2.0"
tags:
- description: A grant is the unit of grant to access certain resource in OPV
  name: Grant
