// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/roney492/opv/pkg/ent/apiaudit"
	"github.com/roney492/opv/pkg/ent/predicate"
)

// APIAuditDelete is the builder for deleting a APIAudit entity.
type APIAuditDelete struct {
	config
	hooks    []Hook
	mutation *APIAuditMutation
}

// Where adds a new predicate to the APIAuditDelete builder.
func (aad *APIAuditDelete) Where(ps ...predicate.APIAudit) *APIAuditDelete {
	aad.mutation.predicates = append(aad.mutation.predicates, ps...)
	return aad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aad *APIAuditDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aad.hooks) == 0 {
		affected, err = aad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*APIAuditMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aad.mutation = mutation
			affected, err = aad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aad.hooks) - 1; i >= 0; i-- {
			mut = aad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aad *APIAuditDelete) ExecX(ctx context.Context) int {
	n, err := aad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aad *APIAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: apiaudit.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: apiaudit.FieldID,
			},
		},
	}
	if ps := aad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aad.driver, _spec)
}

// APIAuditDeleteOne is the builder for deleting a single APIAudit entity.
type APIAuditDeleteOne struct {
	aad *APIAuditDelete
}

// Exec executes the deletion query.
func (aado *APIAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := aado.aad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apiaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aado *APIAuditDeleteOne) ExecX(ctx context.Context) {
	aado.aad.ExecX(ctx)
}
