// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/open-privacy/opv/pkg/ent/fact"
	"github.com/open-privacy/opv/pkg/ent/facttype"
	"github.com/open-privacy/opv/pkg/ent/grant"
	"github.com/open-privacy/opv/pkg/ent/schema"
	"github.com/open-privacy/opv/pkg/ent/scope"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	factMixin := schema.Fact{}.Mixin()
	factMixinFields0 := factMixin[0].Fields()
	_ = factMixinFields0
	factFields := schema.Fact{}.Fields()
	_ = factFields
	// factDescCreatedAt is the schema descriptor for created_at field.
	factDescCreatedAt := factMixinFields0[0].Descriptor()
	// fact.DefaultCreatedAt holds the default value on creation for the created_at field.
	fact.DefaultCreatedAt = factDescCreatedAt.Default.(func() time.Time)
	// factDescUpdatedAt is the schema descriptor for updated_at field.
	factDescUpdatedAt := factMixinFields0[1].Descriptor()
	// fact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fact.DefaultUpdatedAt = factDescUpdatedAt.Default.(func() time.Time)
	// fact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fact.UpdateDefaultUpdatedAt = factDescUpdatedAt.UpdateDefault.(func() time.Time)
	// factDescID is the schema descriptor for id field.
	factDescID := factFields[0].Descriptor()
	// fact.DefaultID holds the default value on creation for the id field.
	fact.DefaultID = factDescID.Default.(func() string)
	facttypeMixin := schema.FactType{}.Mixin()
	facttypeMixinFields0 := facttypeMixin[0].Fields()
	_ = facttypeMixinFields0
	facttypeFields := schema.FactType{}.Fields()
	_ = facttypeFields
	// facttypeDescCreatedAt is the schema descriptor for created_at field.
	facttypeDescCreatedAt := facttypeMixinFields0[0].Descriptor()
	// facttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	facttype.DefaultCreatedAt = facttypeDescCreatedAt.Default.(func() time.Time)
	// facttypeDescUpdatedAt is the schema descriptor for updated_at field.
	facttypeDescUpdatedAt := facttypeMixinFields0[1].Descriptor()
	// facttype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	facttype.DefaultUpdatedAt = facttypeDescUpdatedAt.Default.(func() time.Time)
	// facttype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	facttype.UpdateDefaultUpdatedAt = facttypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// facttypeDescBuiltIn is the schema descriptor for built_in field.
	facttypeDescBuiltIn := facttypeFields[2].Descriptor()
	// facttype.DefaultBuiltIn holds the default value on creation for the built_in field.
	facttype.DefaultBuiltIn = facttypeDescBuiltIn.Default.(bool)
	// facttypeDescID is the schema descriptor for id field.
	facttypeDescID := facttypeFields[0].Descriptor()
	// facttype.DefaultID holds the default value on creation for the id field.
	facttype.DefaultID = facttypeDescID.Default.(func() string)
	grantMixin := schema.Grant{}.Mixin()
	grantMixinFields0 := grantMixin[0].Fields()
	_ = grantMixinFields0
	grantFields := schema.Grant{}.Fields()
	_ = grantFields
	// grantDescCreatedAt is the schema descriptor for created_at field.
	grantDescCreatedAt := grantMixinFields0[0].Descriptor()
	// grant.DefaultCreatedAt holds the default value on creation for the created_at field.
	grant.DefaultCreatedAt = grantDescCreatedAt.Default.(func() time.Time)
	// grantDescUpdatedAt is the schema descriptor for updated_at field.
	grantDescUpdatedAt := grantMixinFields0[1].Descriptor()
	// grant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	grant.DefaultUpdatedAt = grantDescUpdatedAt.Default.(func() time.Time)
	// grant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	grant.UpdateDefaultUpdatedAt = grantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// grantDescID is the schema descriptor for id field.
	grantDescID := grantFields[0].Descriptor()
	// grant.DefaultID holds the default value on creation for the id field.
	grant.DefaultID = grantDescID.Default.(func() string)
	scopeMixin := schema.Scope{}.Mixin()
	scopeMixinFields0 := scopeMixin[0].Fields()
	_ = scopeMixinFields0
	scopeFields := schema.Scope{}.Fields()
	_ = scopeFields
	// scopeDescCreatedAt is the schema descriptor for created_at field.
	scopeDescCreatedAt := scopeMixinFields0[0].Descriptor()
	// scope.DefaultCreatedAt holds the default value on creation for the created_at field.
	scope.DefaultCreatedAt = scopeDescCreatedAt.Default.(func() time.Time)
	// scopeDescUpdatedAt is the schema descriptor for updated_at field.
	scopeDescUpdatedAt := scopeMixinFields0[1].Descriptor()
	// scope.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scope.DefaultUpdatedAt = scopeDescUpdatedAt.Default.(func() time.Time)
	// scope.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scope.UpdateDefaultUpdatedAt = scopeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scopeDescNonce is the schema descriptor for nonce field.
	scopeDescNonce := scopeFields[2].Descriptor()
	// scope.DefaultNonce holds the default value on creation for the nonce field.
	scope.DefaultNonce = scopeDescNonce.Default.(func() string)
	// scopeDescID is the schema descriptor for id field.
	scopeDescID := scopeFields[0].Descriptor()
	// scope.DefaultID holds the default value on creation for the id field.
	scope.DefaultID = scopeDescID.Default.(func() string)
}
