{
 "title": "OPV",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "url",
    "query": {
     "query": "label_values(opv_dataplane_request_duration_seconds_bucket, url)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(opv_dataplane_request_duration_seconds_bucket, code)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(opv_dataplane_request_duration_seconds_bucket, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Plane Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (code, method, url, le) (rate(opv_dataplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (code, method, url, le) (rate(opv_dataplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (code, method, url, le) (rate(opv_dataplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Data Plane Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(opv_dataplane_request_duration_seconds_count{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m]))\n",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Control Plane Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (code, method, url, le) (rate(opv_controlplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (code, method, url, le) (rate(opv_controlplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (code, method, url, le) (rate(opv_controlplane_request_duration_seconds_bucket{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m])))\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Control Plane Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(opv_controlplane_request_duration_seconds_count{code=~\"$code\",method=~\"$method\", url=~\"$url\"}[5m]))\n",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}