package main

import (
	_ "github.com/open-privacy/opv/cmd/dataplane/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/open-privacy/opv/pkg/config"
	"github.com/open-privacy/opv/pkg/dataplane"
	"github.com/tj/go-gracefully"
)

// @title Open Privacy Vault Data Plane API
// @version 1.0
// @description Open Privacy Vault Data Plane API.
// @host localhost
// @basePath /api/v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-OPV-GRANT-KEY

// @tag.name Scope
// @tag.description A scope is the unit of encryption isolation unit, usually it represents a person as a scope

// @tag.name Fact
// @tag.description A fact is the unit of PII information, e.g. email, address, phone number, and etc.
func main() {
	dp := dataplane.MustNewDataPlane()
	dp.Start()
	defer dp.Stop()

	gracefully.Timeout = config.ENV.GracefullyShutdownTimeout
	gracefully.Shutdown()
}
