name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Unit Test
        run: make test

  functional_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Functional Test
        run: |
          make build
          make run &
          sleep 5
          make local_functional_test
          kill -9 `lsof -i:28000 -t`
          kill -9 `lsof -i:27999 -t`

  docs_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Doc Lint
        run: |
          cd ./docs/openprivacy.io
          npm i
          npm test
