name: Functional Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  functional_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Functional Test
        run: |
          make build
          make run &
          sleep 5
          make local_functional_test
          kill -9 `lsof -i:28000 -t`
          kill -9 `lsof -i:27999 -t`
