// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Fact is the predicate function for fact builders.
type Fact func(*sql.Selector)

// Scope is the predicate function for scope builders.
type Scope func(*sql.Selector)
